// Auth0 login Actions
const SET_USER_LOGGED_IN = "SET_USER_LOGGED_IN";

// Custom login Actions
const USER_LOG_IN_BEGIN = "USER_LOG_IN_BEGIN";
const USER_LOG_IN_SUCCESS = "USER_LOG_IN_SUCCESS";
const USER_LOG_IN_ERROR = "USER_LOG_IN_ERROR";

// Sign up actions
const USER_SIGN_UP_BEGIN = "USER_SIGN_UP_BEGIN";
const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
const USER_SIGN_UP_ERROR = "USER_SIGN_UP_ERROR";

const CLEAR_USER_MESSAGE = "CLEAR_USER_MESSAGE";

export {
  SET_USER_LOGGED_IN,
  USER_LOG_IN_BEGIN,
  USER_LOG_IN_SUCCESS,
  USER_LOG_IN_ERROR,
  USER_SIGN_UP_BEGIN,
  USER_SIGN_UP_SUCCESS,
  USER_SIGN_UP_ERROR,
  CLEAR_USER_MESSAGE,
};
