const SET_AUTH_LOADING = "SET_AUTH_LOADING";
const SET_USER_LOGGED_IN = "SET_USER_LOGGED_IN";
const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export { SET_USER_LOGGED_IN, SET_AUTH_LOADING, USER_LOGGED_OUT };
