// List Users
export const ADMIN_LIST_USERS_BEGIN = 'ADMIN_LIST_USERS_BEGIN';
export const ADMIN_LIST_USERS_ERROR = 'ADMIN_LIST_USERS_ERROR';
export const ADMIN_LIST_USERS_SUCCESS = 'ADMIN_LIST_USERS_SUCCESS';

// Delete Mobile
export const ADMIN_DELETE_MOBILE_BEGIN = 'ADMIN_DELETE_MOBILE_BEGIN';
export const ADMIN_DELETE_MOBILE_SUCCESS = 'ADMIN_DELETE_MOBILE_SUCCESS';
export const ADMIN_DELETE_MOBILE_ERROR = 'ADMIN_DELETE_MOBILE_ERROR';

// List Mobiles
export const ADMIN_LIST_MOBILE_BEGIN = 'ADMIN_LIST_MOBILE_BEGIN';
export const ADMIN_LIST_MOBILE_SUCCESS = 'ADMIN_LIST_MOBILE_SUCCESS';
export const ADMIN_LIST_MOBILE_ERROR = 'ADMIN_LIST_MOBILE_ERROR';
