export const CART_ADD_MOBILE_TO_LOCAL_BEGIN = 'CART_ADD_MOBILE_TO_LOCAL_BEGIN';

export const CART_ADD_MOBILE_TO_LOCAL_SUCCESS =
  'CART_ADD_MOBILE_TO_LOCAL_SUCCESS';

export const CART_ADD_MOBILE_TO_LOCAL_ERROR = 'CART_ADD_MOBILE_TO_LOCAL_ERROR';
