const NOTIFICATION_SEND = 'NOTIFICATION_SEND';
const NOTIFICATION_CLEAR = 'NOTIFICATION_CLEAR';

// Authenticate User
const USER_AUTHENTICATION_SUCCESS = 'USER_AUTHENTICATION_SUCCESS';
const USER_AUTHENTICATION_FAIL = 'USER_AUTHENTICATION_FAIL';

// Check is user registered
const USER_REGISTER_CHECK_BEGIN = 'USER_REGISTER_CHECK_BEGIN';
const USER_REGISTER_CHECK_SUCCESS = 'USER_REGISTER_CHECK_SUCCESS';
const USER_REGISTER_CHECK_ERROR = 'USER_REGISTER_CHECK_ERROR';

// Custom login Actions
const USER_SIGN_IN_BEGIN = 'USER_SIGN_IN_BEGIN';
const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
const USER_SIGN_IN_ERROR = 'USER_SIGN_IN_ERROR';

// Sign up actions
const USER_SIGN_UP_BEGIN = 'USER_SIGN_UP_BEGIN';
const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
const USER_SIGN_UP_ERROR = 'USER_SIGN_UP_ERROR';

// CLEAR_MESSAGE
const USER_CLEAR_SIGNUP_STATUS = 'USER_CLEAR_SIGNUP_STATUS';

// Account Info Action
const USER_INFO_BEGIN = 'USER_INFO_BEGIN';
const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
const USER_INFO_ERROR = 'USER_INFO_ERROR';

// Custom User Log Out
const USER_LOG_OUT_BEGIN = 'USER_LOG_OUT_BEGIN';
const USER_LOG_OUT_SUCCESS = 'USER_LOG_OUT_SUCCESS';
const USER_LOG_OUT_ERROR = 'USER_LOG_OUT_ERROR';

// Update User log constants
const USER_UPDATE_BEGIN = 'USER_UPDATE_BEGIN';
const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR';

// Change Display picture
const USER_CHANGE_DP_BEGIN = 'USER_CHANGE_DP_BEGIN';
const USER_CHANGE_DP_SUCCESS = 'USER_CHANGE_DP_SUCCESS';
const USER_CHANGE_DP_ERROR = 'USER_CHANGE_DP_ERROR';

export {
  USER_SIGN_IN_BEGIN,
  USER_SIGN_IN_SUCCESS,
  USER_SIGN_IN_ERROR,
  USER_SIGN_UP_BEGIN,
  USER_SIGN_UP_SUCCESS,
  USER_SIGN_UP_ERROR,
  NOTIFICATION_SEND,
  NOTIFICATION_CLEAR,
  USER_CLEAR_SIGNUP_STATUS,
  USER_INFO_BEGIN,
  USER_INFO_SUCCESS,
  USER_INFO_ERROR,
  USER_LOG_OUT_BEGIN,
  USER_LOG_OUT_SUCCESS,
  USER_LOG_OUT_ERROR,
  USER_REGISTER_CHECK_BEGIN,
  USER_REGISTER_CHECK_SUCCESS,
  USER_REGISTER_CHECK_ERROR,
  USER_AUTHENTICATION_SUCCESS,
  USER_AUTHENTICATION_FAIL,
  USER_UPDATE_BEGIN,
  USER_UPDATE_SUCCESS,
  USER_UPDATE_ERROR,
  USER_CHANGE_DP_BEGIN,
  USER_CHANGE_DP_SUCCESS,
  USER_CHANGE_DP_ERROR,
};
