const SEND_NOTIFICATION = 'SEND_NOTIFICATION';

// Authenticate User
const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
const AUTHENTICATE_USER_FAIL = 'AUTHENTICATE_USER_FAIL';

// Auth0 login Actions
const USER_LOGGED_IN_USING_AUTH = 'USER_LOGGED_IN_USING_AUTH';

const IS_EMAIL_REGISTERED_BEGIN = 'IS_EMAIL_REGISTERED_BEGIN';
const IS_EMAIL_REGISTERED_SUCCESS = 'IS_EMAIL_REGISTERED_SUCCESS';
const IS_EMAIL_REGISTERED_ERROR = 'IS_EMAIL_REGISTERED_ERROR';

// Custom login Actions
const USER_LOG_IN_BEGIN = 'USER_LOG_IN_BEGIN';
const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_SUCCESS';
const USER_LOG_IN_ERROR = 'USER_LOG_IN_ERROR';

// Sign up actions
const USER_SIGN_UP_BEGIN = 'USER_SIGN_UP_BEGIN';
const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
const USER_SIGN_UP_ERROR = 'USER_SIGN_UP_ERROR';

const CLEAR_USER_MESSAGE = 'CLEAR_USER_MESSAGE';
const CLEAR_USER_SIGNUP_SUCCESS = 'CLEAR_USER_SIGNUP_SUCCESS';

// Account Info Action
const ACCOUNT_INFO_BEGIN = 'ACCOUNT_INFO_BEGIN';
const ACCOUNT_INFO_SUCCESS = 'ACCOUNT_INFO_SUCCESS';
const ACCOUNT_INFO_ERROR = 'ACCOUNT_INFO_ERROR';

// Custom User Log Out
const USER_LOG_OUT_BEGIN = 'USER_LOG_OUT_BEGIN';
const USER_LOG_OUT_SUCCESS = 'USER_LOG_OUT_SUCCESS';
const USER_LOG_OUT_ERROR = 'USER_LOG_OUT_ERROR';

// Update User log constants
const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

// Change Display picture
const CHANGE_DP_BEGIN = 'CHANGE_DP_BEGIN';
const CHANGE_DP_SUCCESS = 'CHANGE_DP_SUCCESS';
const CHANGE_DP_ERROR = 'CHANGE_DP_ERROR';

export {
  USER_LOGGED_IN_USING_AUTH,
  USER_LOG_IN_BEGIN,
  USER_LOG_IN_SUCCESS,
  USER_LOG_IN_ERROR,
  USER_SIGN_UP_BEGIN,
  USER_SIGN_UP_SUCCESS,
  USER_SIGN_UP_ERROR,
  CLEAR_USER_MESSAGE,
  CLEAR_USER_SIGNUP_SUCCESS,
  ACCOUNT_INFO_BEGIN,
  ACCOUNT_INFO_SUCCESS,
  ACCOUNT_INFO_ERROR,
  USER_LOG_OUT_BEGIN,
  USER_LOG_OUT_SUCCESS,
  USER_LOG_OUT_ERROR,
  IS_EMAIL_REGISTERED_BEGIN,
  IS_EMAIL_REGISTERED_SUCCESS,
  IS_EMAIL_REGISTERED_ERROR,
  AUTHENTICATE_USER_SUCCESS,
  AUTHENTICATE_USER_FAIL,
  UPDATE_USER_BEGIN,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_ERROR,
  SEND_NOTIFICATION,
  CHANGE_DP_BEGIN,
  CHANGE_DP_SUCCESS,
  CHANGE_DP_ERROR,
};
