export const FILTER_MOBILE_GET_ALL = 'FILTER_MOBILE_GET_ALL';

export const FILTER_MOBILE_SET = 'FILTER_MOBILE_SET';

export const FILTER_MOBILE_SORT = 'FILTER_MOBILE_SORT';

export const FILTER_MOBILE_BY_BRAND = 'FILTER_MOBILE_BY_BRAND';

export const FILTER_MOBILE_BY_STAR = 'FILTER_MOBILE_BY_STAR';

export const FILTER_MOBILE_BY_PRICE = 'FILTER_MOBILE_BY_PRICE';

export const FILTER_MOBILE_BY_RAM = 'FILTER_MOBILE_BY_RAM';
