export const MOBILE_CREATE_BEGIN = 'MOBILE_CREATE_BEGIN';
export const MOBILE_CREATE_SUCCESS = 'MOBILE_CREATE_SUCCESS';
export const MOBILE_CREATE_ERROR = 'MOBILE_CREATE_ERROR';

export const MOBILE_LIST_BEGIN = 'MOBILE_LIST_BEGIN';
export const MOBILE_LIST_SUCCESS = 'MOBILE_LIST_SUCCESS';
export const MOBILE_LIST_ERROR = 'MOBILE_LIST_ERROR';

export const MOBILE_CLEAR_SAVED = 'MOBILE_CLEAR_SAVED';
