// Crate an Order, razorpay
export const PAYMENT_RAZORPAY_CREATE_AN_ORDER_BEGIN =
  'PAYMENT_RAZORPAY_CREATE_AN_ORDER_BEGIN';

export const PAYMENT_RAZORPAY_CREATE_AN_ORDER_SUCCESS =
  'PAYMENT_RAZORPAY_CREATE_AN_ORDER_SUCCESS';

export const PAYMENT_RAZORPAY_CREATE_AN_ORDER_ERROR =
  'PAYMENT_RAZORPAY_CREATE_AN_ORDER_ERROR';
