export const SELLER_MOBILE_LIST_BEGIN = 'SELLER_MOBILE_LIST_BEGIN';
export const SELLER_MOBILE_LIST_SUCCESS = 'SELLER_MOBILE_LIST_SUCCESS';
export const SELLER_MOBILE_LIST_ERROR = 'SELLER_MOBILE_LIST_ERROR';
