export const SIGN_IN_VIA_GOOGLE_BEGIN = 'SIGN_IN_VIA_GOOGLE_BEGIN';
export const SIGN_IN_VIA_GOOGLE_SUCCESS = 'SIGN_IN_VIA_GOOGLE_SUCCESS';
export const SIGN_IN_VIA_GOOGLE_ERROR = 'SIGN_IN_VIA_GOOGLE_ERROR';
